wk9 - Capstone #3/team3-c-week9-pair-exercises/m3-w3d3-csharp-capstone/Capstone.Web/Models/Park.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Capstone.Web.Models;

namespace Capstone.Web.Models
{
    public class Park
    {
        public string ParkCode { get; set; }
        public string ParkName { get; set; }
        public string State { get; set; }
        public int Acreage { get; set; }
        public int ElevationInFeet { get; set; }
        public double MilesOfTrail { get; set; }
        public int NumberOfCampsites { get; set; }
        public string Climate { get; set; }
        public int YearFounded { get; set; }
        public int AnnualVisitorCount { get; set; }
        public string InspirationalQuote { get; set; }
        public string InspirationalQuoteSource { get; set; }
        public string ParkDescription { get; set; }
        public int EntryFee { get; set; }
        public int NumberOfAnimalSpecies { get; set; }
    }
}

wk9 - Capstone #3/team3-c-week9-pair-exercises/m3-w3d3-csharp-capstone/Capstone.Web/Controllers/ParkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Web.DAL;
using Capstone.Web.Models;

namespace Capstone.Web.Controllers
{
    public class ParkController : Controller
    {
        IParkDAO dal;
        IWeatherDAO dal2;

        public ParkController(IParkDAO dal, IWeatherDAO dal2)
        {
            this.dal = dal;
            this.dal2 = dal2;
        }

        // GET: Park
        public ActionResult Index()
        {

            List<Park> parks = dal.GetAllParks();

            return View("Index", parks);
        }

        // GET: Park/Details
        public ActionResult Details(string id)
        {
            ParkDetails model = new ParkDetails();
            model.Weather = dal2.GetForcast(id);
            model.Park = dal.GetParkDetails(id);

            if (Session["TempUnit"] == null)
            {

                foreach (Weather weather in model.Weather)
                {
                    weather.Unit = 'F';
                    weather.Farhrenheit = true;
                    Session["TempUnit"] = weather.Unit;
                }
            }
            else if ((char)Session["TempUnit"] == 'C')
            {
                Session["TempUnit"] = 'F';
                foreach (Weather weather in model.Weather)
                {
                    weather.Unit = 'F';
                    weather.TempConversion('F');
                    weather.Celcius = true;
                    Session["TempUnit"] = weather.Unit;
                }
            }
            else
            {
                Session["TempUnit"] = 'C';
            }
            return View("Details", model);
        }
        
        //if (Session["TempUnit"] == null)
        //{
        //    Session["TempUnit"] = 'F';
        //}
        //else if ((bool)Session["ShouldUnitChange"])
        //{
        //    if ((char)Session["TempUnit"] == 'F')
        //    {
        //        foreach (Weather weather in model.Weather)
        //        {
        //            weather.TempConversion((char)Session["TempUnit"]);
        //        }
        //        Session["TempUnit"] = 'C';
        //    }
        //    else if ((char)Session["TempUnit"] == 'C')
        //    {
        //        Session["TempUnit"] = 'F';
        //    }
        //    Session["ShouldUnitChange"] = false;
        //}
        //else if ((char)Session["TempUnit"] == 'C')
        //{
        //    foreach (Weather weather in model.Weather)
        //    {
        //        weather.TempConversion('F');
        //    }
        //    if ((bool)Session["ShouldUnitChange"])
        //    {

        //        foreach (Weather weather in model.Weather)
        //        {
        //            weather.TempConversion((char)Session["TempUnit"]);
        //        }
        //        Session["TempUnit"] = 'F';
        //    }
        //}

        //address case for where the Session is already in Cel 'C'

        //model.Park = dal.GetParkDetails(id);
        //Session["TempUnit"] = model;
        //return View("Details", Session["TempUnit"]);


        public ActionResult ChangeTemperatureUnit(string parkCode)
        {

            ParkDetails model = new ParkDetails();
            model.Park = dal.GetParkDetails(parkCode);
            model.Weather = dal2.GetForcast(parkCode);

            foreach (Weather weather in model.Weather)
            {
                if (Session["TempUnit"] == null)
                {
                    weather.Farhrenheit = true;
                    weather.Celcius = false;
                    weather.Unit = 'F';
                }
                else if ((char)Session["TempUnit"] == 'F')
                {
                    weather.Farhrenheit = false;
                    weather.Celcius = true;
                    weather.Unit = 'C';

                }
                else
                {
                    weather.Celcius = false;
                    weather.Farhrenheit = true;
                    weather.Unit = 'F';
                }
            }

            return RedirectToAction("Details", new { id = parkCode });
        }

    }
}

wk9 - Capstone #3/team3-c-week9-pair-exercises/m3-w3d3-csharp-capstone/Capstone.Web/Views/Park/Details.cshtml
@using System.Reflection
@using Capstone.Web.Models
@model Capstone.Web.Models.ParkDetails

<body>
<div class="row">
    <img src="~/Content/img/parks/@(Model.Park.ParkCode).jpg" style="display: block; margin-left: auto; margin-right: auto; width: 60%;" alt="" />
    <div class=" column">
        <p><h2>@Model.Park.ParkName<span style="font-size:medium; font-weight:bold; font-style:italic"> Founded in @Model.Park.YearFounded</span></h2></p>
        <p><h4 style="font-style:italic; text-align:center">"@Model.Park.InspirationalQuote" -@Model.Park.InspirationalQuoteSource</h4></p>
    </div>
    <div class="column">
        <ul font-weight:bold">
            <li>ParkCode : @Model.Park.ParkCode</li>
            <li>State : @Model.Park.State</li>
            <li>Entrance fee: @Model.Park.EntryFee.ToString("c")</li>
            <li>Acerage : @Model.Park.Acreage.ToString("n0")</li>
            <li>Elevation(ft.) : @Model.Park.ElevationInFeet.ToString("n0")</li>
            <li>Miles of trail : @Model.Park.MilesOfTrail.ToString("n0")</li>
            <li>Number of Campsites : @Model.Park.NumberOfCampsites</li>
            <li>Number of Species present: @Model.Park.NumberOfAnimalSpecies.ToString("n0")</li>
            <li>Annual Visitors: @Model.Park.AnnualVisitorCount.ToString("n0")</li>
        </ul>
    </div>

</div>
<br />
<p style="text-align:center"><h4>@Model.Park.ParkDescription</h4></p>
<br />


<div class="row">
    @foreach (Weather weather in Model.Weather)
    {
        <div class="column">
            <p>Day:    @weather.FiveDayForecastValue</p>
            <p><img src="~/Content/img/weather/@(weather.Forecast).png" style="width:65px; height:auto"></p>
            <p>High:   @weather.High°@weather.Unit </p>
            <p>Low:    @weather.Low°@weather.Unit </p>
            @{
                switch (weather.Forecast)
                {
                    case ("rain"):
                        <p>Pack rain gear and wear waterproof shoes!</p>;
                        break;
                    case ("snow"):
                        <p>Pack some snowshoes!</p>;
                        break;
                    case ("thunderstorms"):
                        <p>Seek shelter and avoid hiking on exposed ridges!</p>;
                        break;
                    case ("sunny"):
                        <p>Make sure to pack and wear some sunblock!</p>;
                        break;
                    default:
                        <p>Have fun!</p>;
                        break;
                }


                if ((weather.High >= 75 && weather.Farhrenheit == true) || (weather.High >= 24 && weather.Celcius == true))
                {
                    <p>Bring an extra gallon of water!</p>
                }
                else if ((weather.Low <= 20 && weather.Farhrenheit == true) || weather.Low <= -6 && weather.Celcius == true)
                {
                    <p>Hypothermia is dangerous, be sure to dress warm</p>
                }
                else if ((weather.High - weather.Low) >= 20)
                {
                    <p>Wear breathable layers</p>
                }
            }
        </div>

    }
</div>
@using (Html.BeginForm("ChangeTemperatureUnit", "Park"))
{
    @Html.Hidden("parkCode", Model.Park.ParkCode)
    <button>Convert Temperature Unit</button>
}
</body>

wk9 - Capstone #3/team3-c-week9-pair-exercises/m3-w3d3-csharp-capstone/Capstone.Web/Views/Park/Index.cshtml
@using Capstone.Web.Models
@model IEnumerable<Capstone.Web.Models.Park>

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @foreach (var item in Model)
    {

        <div class="row">
            <div class="column">
                <a href='@Url.Action("Details", "Park", new { id = item.ParkCode }, null)'>
                    <img src="~/Content/img/parks/@(item.ParkCode).jpg" alt="" />
                </a>
            </div>
            <div class="column">
                <h3>@Html.DisplayFor(modelItem => item.ParkName) - @Html.DisplayFor(modelItem => item.State)</h3>
                <p>@Html.DisplayFor(modelItem => item.ParkDescription)</p>
                <p>@Html.ActionLink("More Info", "Details", "Park", new { id = item.ParkCode }, null) </p>
            </div>
        </div>
    }
</body>
</html>